#!/bin/bash

# create a bootstrap: cd directory && zip -r ~/bootstrap.zip blocks/ chainstate/

################################################################################

source /etc/freedom-node/include/color

################################################################################

# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"
# user
USER_NAME="$(cat /etc/freedom-node/user 2>/dev/null)"

################################################################################
# bootstrap download & install
################################################################################

# if missing
if [[ ! -d "$HOME_DIR"/.trumpcoin/bootstrap/ ]] &>/dev/null; then

  printf '%b' "[  ${G1}OK${N0}  ] Deleting corrupt or old data..\n"
  # cleanup corrupt, old data
  rm -rf "$HOME_DIR"/.trumpcoin/blocks/
  rm -rf "$HOME_DIR"/.trumpcoin/chainstate/
  rm -rf "$HOME_DIR"/.trumpcoin/database/
  rm -rf "$HOME_DIR"/.trumpcoin/evodb/
  rm -rf "$HOME_DIR"/.trumpcoin/sporks/
  rm -rf "$HOME_DIR"/.trumpcoin/zerocoin/
  rm -rf "$HOME_DIR"/.trumpcoin/mempool.dat
  rm -rf "$HOME_DIR"/.trumpcoin/peers.dat
  rm -rf "$HOME_DIR"/.trumpcoin/banlist.dat
  rm -rf "$HOME_DIR"/.trumpcoin/mncache.dat
  rm -rf "$HOME_DIR"/.trumpcoin/mnpayments.dat
  rm -rf "$HOME_DIR"/.trumpcoin/budget.dat

  # if enough space greater than ng
  if [[ "$(df -h --total | tail -1 | xargs | tr -d '-' | awk '{ print $4 }' | tr -d 'G' | tr -d '.')" -gt "10" ]] &>/dev/null; then

    printf '%b' "[  ${G1}OK${N0}  ] Downloading bootstrap.zip..\n"
    # bootstrap url
    BOOTSTRAP_URL="http://45.92.11.251/blocks/bootstrap.zip"
    # bootstrap file
    OUTPUT_FILE="$(echo "$BOOTSTRAP_URL" | awk -F/ '{ print $NF }')"
    cd || exit
    ############################################################################
    # start/continue the download
    curl -L -O "$BOOTSTRAP_URL"
    ############################################################################
    RESULT=$?
    # if any result
    if [ ! $RESULT == "0" ] &>/dev/null; then
      echo "[  !!  ] Download failed"
      sleep 1
    fi

    ############################################################################

    # kill wallet
    kill -9 "$(pidof freedomcoind 2>/dev/null)" &>/dev/null

    ############################################################################

    # backup wallet.dat
    printf '%b' "[  ${G1}OK${N0}  ] Creating wallet.dat backup..\n"
    cp "$HOME_DIR"/.trumpcoin/wallet.dat /home/"$USER_NAME"/node/ "$HOME" &>/dev/null
    # remove old blockchain files and folders
    printf '%b' "[  ${G1}OK${N0}  ] Removing old blockchain..\n"
    rm -rf "$HOME_DIR"/.trumpcoin/* &>/dev/null
    # restore wallet.dat backup
    printf '%b' "[  ${G1}OK${N0}  ] Restoring wallet.dat backup..\n"
    mv /home/"$USER_NAME"/node/wallet.dat "$HOME_DIR"/.trumpcoin 2>/dev/null

    ############################################################################

    # unzip bootstrap.zip
    printf '%b' "[  ${G1}OK${N0}  ] Extracting bootstrap.zip..\n"
    unzip "$HOME_DIR"/bootstrap.zip -d "$HOME_DIR"/.trumpcoin

    ############################################################################

    # remove blockchain.zip
    printf '%b' "[  ${G1}OK${N0}  ] Removing bootstrap.zip..\n"
    rm "$HOME_DIR"/bootstrap.zip &>/dev/null
    # make directory for stopping this
    mkdir "$HOME_DIR"/.trumpcoin/bootstrap &>/dev/null

    ############################################################################

    # move blockchain out of bootstrap folder
    printf '%b' "[  ${G1}OK${N0}  ] Installing blockchain..\n"
    mv "$HOME_DIR"/.trumpcoin/bootstrap/* "$HOME_DIR"/.trumpcoin 2>/dev/null
  else
    printf '%b' "[  ${G1}OK${N0}  ] Not enouh space for bootstrap.zip, skipping! ${GR}Brace yourself, Mmmmm coffeee..${N0}\n"
    mkdir "$HOME_DIR"/.trumpcoin/bootstrap &>/dev/null
  fi
fi

# END
