#!/bin/bash

export TERM=linux

################################################################################

# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

################################################################################
# display (touchscreen)
################################################################################

# if any display
if [[ -f "$HOME_DIR"/node/display ]] &>/dev/null; then
  pkill -f /etc/freedom-node/include/display/listener
  bash /etc/freedom-node/include/display/listener &
fi

################################################################################

for (( ; ; )); do # loop dashbord

  source /etc/freedom-node/include/functions
  source /etc/freedom-node/include/color

  clear
  printf '%b' "
${GR:?}                 ${GR:?} Freedom-node ${REPO_VERSION:?}   $SYSTEM_DATE ${SYSTEM_CLOCK:?}
${CB:?}    /#########   ${N0:?} Patriotnode + Stakebox       ${MASTER_STATUS:?} ${CONTROL_STATUS:?} ${POS_STATUS:?} ${TOR_STATUS:?} ${LAN_STATUS:?}
${CB:?}   | ##______/   ${GR:?} -----------------------------------------${N0:?}
${CB:?}   | ##          ${N0:?} Load ${SYSTEM_LOAD:?} temp ${CPU_CTEMP_C:?} ${CPU_FTEMP:?}
${CB:?}   | ######      ${N0:?} FreeMem ${FREE_MEM:?}/${TOTAL_MEM:?} HDDuse ${USED_HDD:?}/${TOTAL_HDD} (${USED_HDD_P:?})
${CB:?}   | ##___/      ${N0:?} ${SYSTEM_USER:?}@${IP_ADDRESS:?} ${G0:?}⇩${N0:?} ${DOWNLOAD:?} ${R1:?}⇧${N0:?} ${UPLOAD:?}
${CB:?}   | ##          ${N0:?} ${WALLET_DAEMON:?} ${WALLET_VERSION:?} ${WALLET_CHAIN:?} Sync ${WALLET_SYNC:?}
${CB:?}   | ##          ${N0:?} WAN ${PUBLIC_IP:?} Peers ${WALLET_PEERS_TOTAL:?} ${WALLET_PEERS_IP4:?} ${WALLET_PEERS_IP6:?}
${CB:?}   | ##          ${N0:?}
${CB:?}   |__/          ${N0:?} Balance ${WALLET_BALANCES:?} ${WALLET_POS_REWARDS:?} ${WALLET_INPUTS_NODES:?}
${CB:?}                 ${N0:?} TxCount ${WALLET_TXCOUNT:?} Mempool ${WALLET_MEMPOOL:?} Block ${WALLET_HEADS:?}
${CB:?}   FreedomCoin   ${N0:?} ${TIMELINE:?}

${TX:?}${WALLET_TXLAST:?}

${LAST_LOG:?}
"

  # wait for n second before updating
  sleep "${TIME:?}"
done

# END
