#!/bin/bash

################################################################################

source /etc/freedom-node/include/color

################################################################################

# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"
# user
USER_NAME="$(cat /etc/freedom-node/user 2>/dev/null)"

################################################################################

RANDOM_INFOS=$((((RANDOM % 2) + 1)))

################################################################################
# random infos
################################################################################

if [[ "$RANDOM_INFOS" == "2" ]] &>/dev/null; then
  # random quotes/information start
  RANDOM_INFO=$((((RANDOM % 3) + 1)))
  # information - system - wallet
  if [ "$RANDOM_INFO" -eq "1" ] &>/dev/null; then
    TIMELINE="Value: $WALLET_VALUE USD ($FREED_PRICE)"
  fi
elif [ "$RANDOM_INFO" -eq "2" ] &>/dev/null; then
  TIMELINE="Difficulty: $(grep "difficulty" "$HOME_DIR"/node/getinfo.tmp 2>/dev/null | awk '{ print $NF }' | tr -d ',')"
elif [ "$RANDOM_INFO" -eq "3" ] &>/dev/null; then
  TIMELINE="Nodes: $(grep "total" "$HOME_DIR"/node/getpatriotnodecount.tmp | awk '{ print $NF }') IPv4: $(grep "ipv4" "$HOME_DIR"/node/getpatriotnodecount.tmp | awk '{ print $NF }') IPv6: $(grep "ipv6" "$HOME_DIR"/node/getpatriotnodecount.tmp | awk '{ print $NF }')"
elif [ "$RANDOM_INFO" -eq "4" ] &>/dev/null; then
  LOWEST_INPUT="$(grep "amount" "$HOME_DIR"/node/listunspent.tmp 2>/dev/null | awk '{ print $NF }' | tr -d ',' | sort -n | tail -1)"
  # if any data
  if [[ -n "$HIGHEST_INPUT" ]] &>/dev/null; then
    HIGHEST_INPUT_VALUE="$(echo "${HIGHEST_INPUT}*${FREED_PRICE}" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    LOWEST_INPUT_VALUE="$(echo "${LOWEST_INPUT}*${FREED_PRICE}" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    # if zero
    if [[ -z "$LOWEST_INPUT_VALUE" ]] &>/dev/null; then
      LOWEST_INPUT_VALUE="0"
    else
      LOWEST_INPUT_VALUE="${G1}$LOWEST_INPUT_VALUE${N0}"
    fi
    TIMELINE="Lowest input: $LOWEST_INPUT Value: $LOWEST_INPUT_VALUE USD"
  else
    TIMELINE="Lowest input: ${GR}No coins..${N0}"
  fi
elif [ "$RANDOM_INFO" -eq "5" ] &>/dev/null; then
  HIGHEST_INPUT="$(grep "amount" "$HOME_DIR"/node/listunspent.tmp 2>/dev/null | awk '{ print $NF }' | tr -d ',' | sort -n | head -1)"
  # if any data
  if [[ -n "$HIGHEST_INPUT" ]] &>/dev/null; then
    HIGHEST_INPUT_VALUE="$(echo "${HIGHEST_INPUT}*${FREED_PRICE}" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }')"
    # if zero
    if [[ -z "$HIGHEST_INPUT_VALUE" ]] &>/dev/null; then
      HIGHEST_INPUT_VALUE="0"
    else
      HIGHEST_INPUT_VALUE="${G1}$HIGHEST_INPUT_VALUE${N0}"
    fi
    TIMELINE="Highest input: $HIGHEST_INPUT Value: $HIGHEST_INPUT_VALUE USD"
  else
    TIMELINE="Highest input: ${GR}No coins..${N0}"
  fi
fi

# if zero
if [[ "$(grep -c "true" /etc/freedom-node/mnsync_status.tmp)" -eq "0" ]] &>/dev/null; then
  # still syncing, just quote
  RANDOM_INFOS="2"
fi

################################################################################
# random quotes
################################################################################

if [[ "$RANDOM_INFOS" == "2" ]] &>/dev/null; then
  # random quotes/information start
  RANDOM_QUOTES=$((((RANDOM % 11) + 1)))
  # quotes - art of the deal, djt
  if [ "$RANDOM_QUOTES" -eq "1" ] &>/dev/null; then
    TIMELINE="${GR}Think big${N0:?}"
  elif [ "$RANDOM_QUOTES" -eq "2" ] &>/dev/null; then
    TIMELINE="${GR}Maximize your options${N0:?}"
  elif [ "$RANDOM_QUOTES" -eq "3" ] &>/dev/null; then
    TIMELINE="${GR}Know your market${N0:?}"
  elif [ "$RANDOM_QUOTES" -eq "4" ] &>/dev/null; then
    TIMELINE="${GR}Use your leverage${N0:?}"
  elif [ "$RANDOM_QUOTES" -eq "5" ] &>/dev/null; then
    TIMELINE="${GR}Enhance your location${N0:?}"
  elif [ "$RANDOM_QUOTES" -eq "6" ] &>/dev/null; then
    TIMELINE="${GR}Get the word out${N0:?}"
  elif [ "$RANDOM_QUOTES" -eq "7" ] &>/dev/null; then
    TIMELINE="${GR}Fight back${N0:?}"
  elif [ "$RANDOM_QUOTES" -eq "8" ] &>/dev/null; then
    TIMELINE="${GR}Deliver the goods${N0:?}"
  elif [ "$RANDOM_QUOTES" -eq "9" ] &>/dev/null; then
    TIMELINE="${GR}Contain the costs${N0:?}"
  elif [ "$RANDOM_QUOTES" -eq "10" ] &>/dev/null; then
    TIMELINE="${GR}Have fun${N0:?}"
  elif [ "$RANDOM_QUOTES" -eq "11" ] &>/dev/null; then
    TIMELINE="${GR}Fight! Fight! Fight!${N0:?}"
  fi
fi

# if zero
if [[ -z "$TIMELINE" ]] &>/dev/null; then
  TIMELINE="Always something.."
fi

################################################################################
# random quotes from quote database
################################################################################

# random quote age (seconds)
RANDOM_QUOTE_AGE="$(stat -c '%Y' /home/"$USER_NAME"/node/rq.tmp 2>/dev/null | while read lastedit; do echo "$(($(echo "$DATE") - $lastedit))"; done)"

# if missing, if older than n, less than n
if [[ ! -f /home/"$USER_NAME"/node/rq.tmp || "$RANDOM_QUOTE_AGE" -gt "$(echo "180+$(wc -l /home/"$USER_NAME"/node/quotes 2>/dev/null | awk '{ print $1 }')" | bc 2>/dev/null)" || "$(wc -l /home/"$USER_NAME"/node/rq.tmp | awk '{ print $1 }')" -lt "2" ]] &>/dev/null; then
  # fetch quotes with proxy from quotedb
  curl -s --proxy socks5h://localhost:9050 https://www.quotedb.com/quote/quote.php?action=random_quote_rss >/home/"$USER_NAME"/node/rq.tmp 2>/dev/null
fi

RANDOM_QUOTES="$(html2text /home/"$USER_NAME"/node/rq.tmp 2>/dev/null | egrep -v "www|Image" | sed '/^[[:space:]]*$/d' | paste -sd' ')"
RANDOM_AUTHOR="$(html2text /home/"$USER_NAME"/node/rq.tmp 2>/dev/null | grep "authors" | tr '/' ' ' | awk -Fauthors '{ print $2 }' | xargs)"

# create quotes
echo "$RANDOM_QUOTES --$RANDOM_AUTHOR" >>/home/"$USER_NAME"/node/quotes
# disregard duplicates, sort randomly, disregard lines greater than n, html loc, errors
echo "$(tail -777 /home/"$USER_NAME"/node/quotes 2>/dev/null | awk 'length($0)<171' | awk '!a[$0]++' | sort -R | egrep -v ";|<|>|{|}|502 Bad Gateway|error code: 524|error code: 504")" >/home/"$USER_NAME"/node/quotes

# if found
if [[ -f /home/"$USER_NAME"/node/quotes.banned ]] &>/dev/null; then
  # banned quotes by authors
  echo "$(sort /home/"$USER_NAME"/node/quotes | grep -v "$(awk NF /home/"$USER_NAME"/node/quotes.banned)")" >/home/"$USER_NAME"/node/quotes
fi

# if enough quotes
if [[ "$(wc -l /home/"$USER_NAME"/node/quotes 2>/dev/null | awk '{ print $1 }')" -gt "10" ]] &>/dev/null; then
  # random quote log start
  RANDOM_QUOTE_LOG=$((((RANDOM % 2) + 1)))
  if [[ "$RANDOM_QUOTE_LOG" == "1" ]] &>/dev/null; then
    LAST_LOG_QUOTE="1"
  else
    LAST_LOG_QUOTE="0"
  fi
fi

# END
