#!/bin/bash

################################################################################

# colors
B0='\e[34m'   # Blue
B1='\e[94m'   # Blue light
CY='\e[36m'   # Cyan
C1='\e[96m'   # Cyan light
G0='\e[32m'   # Green
G1='\e[92m'   # Green light
GR='\e[90m'   # Grey
N0='\033[0m'  # No color
P0='\e[0;35m' # Purple
P1='\e[1;35m' # Purple light
R0='\e[31m'   # Red
R1='\e[91m'   # Red light
Y0='\e[33m'   # Yellow
Y1='\e[93m'   # Yellow light
BLD='\e[1m'   # Bold\brighter

################################################################################

clear
printf '%b' "${Y0}${BLD}
F   R   E   E   D   O   M   C   O   I   N${B1}

@${N0}@${B1}@${N0}  @${B1}@${N0}@${B1}    @${N0}@${B1}@${N0}@${B1}@${N0}@${B1}    @${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@${N0}    @${B1}@${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@${N0}
${B1}@${N0}@${B1}@${N0}@${B1} @${N0}@${B1}@${N0}   @${B1}@${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@   ${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@   ${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@${N0}
${N0}@${B1}@${N0}!${B1}@${N0}!${B1}@${N0}@${B1}@   ${N0}@${B1}@${N0}!  ${B1}@${N0}@${B1}@   ${N0}@${B1}@${N0}!  ${B1}@${N0}@${B1}@   ${N0}@${B1}@${N0}!
!@!!@!@!   !@!  @!@   !@!  @!@   !@!${R1}
@!@ !!@!   @!@  !@!   @!@  !@!   @!!!:!${N0}
!@!  !!!   !@!  !!!   !@!  !!!   !!!!!:${R1}
!!:  !!!   !!:  !!!   !!:  !!!   !!:${N0}
:!:  !:!   :!:  !:!   :!:  !:!   :!:${R1}
::   ::    :::: ::    :::: ::    :: ::::${N0}
::    :     : :  :    :: :  :    : :: ::${R1}

${GR}The original TrumpCoin!${N0}

Installing Freedom node! ${GR}Version 1${N0}
\n"

################################################################################
# repository updates
################################################################################

# any updates
printf '%b' "[${N0}!!${N0}] :: Updating freedom-node repository..\n"
printf '%b' "[${G1}OK${N0}] :: $(cd || exit && cd freedom-node && git pull)\n"

################################################################################
# freedom-node directory & user
################################################################################

# if missing
if [[ ! -d /etc/freedom-node ]] &>/dev/null; then
  printf '%b' "[${N0}!!${N0}] :: Creating freedom-node directory..\n"
fi

# create install directory
sudo mkdir /etc/freedom-node &>/dev/null
# fix ownership for freedom-node (whoami)
sudo chown -R "$(whoami)":"$(whoami)" /etc/freedom-node/ 2>/dev/null

# fetch user
echo "$(whoami)" >/etc/freedom-node/user
# user name
USER_NAME="$(cat /etc/freedom-node/user 2>/dev/null)"
printf '%b' "[${G1}OK${N0}] :: USER_NAME=${G1}$USER_NAME${N0}\n" && sleep 1

# fetch home directory
echo "$HOME" >/etc/freedom-node/homedir
# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"
printf '%b' "[${G1}OK${N0}] :: HOME_DIR=${G1}$HOME_DIR${N0}\n" && sleep 1

################################################################################
# .trumpcoin directory
################################################################################

# if missing
if [[ ! -d "$HOME"/.trumpcoin ]] &>/dev/null; then
  printf '%b' "[${N0}!!${N0}] :: Creating .trumpcoin directory..\n"
  # create wallet directory
  mkdir "$HOME"/.trumpcoin &>/dev/null
fi

# fix ownership for trumpcoin
sudo chown -R "$USER_NAME":"$USER_NAME" "$HOME_DIR"/.trumpcoin/ 2>/dev/null

################################################################################
# install files & create executable
################################################################################

# install freedom-node files
cd || exit && cp -rf freedom-node/include /etc/freedom-node
# create executable file
chmod +x "$USER_NAME":"$USER_NAME" /etc/freedom-node/include/start 2>/dev/null

################################################################################
# requirements
################################################################################

# not installed
if ! [ -x "$(command -v ifconfig)" ]; then
  printf '%b' "[${GR}!!${N0}] :: Installing net-tools!\n"
  sudo apt-get install net-tools -y
  if [ $? -eq 0 ]; then
    printf '%b' "[${G1}OK${N0}] :: net-tools installed!\n"
  fi
fi

# not installed
if [[ ! "$(curl --version)" ]] &>/dev/null; then
  printf '%b' "[${GR}!!${N0}] :: Installing curl!\n"
  sudo apt-get install curl -y
  if [ $? -eq 0 ]; then
    printf '%b' "[${G1}OK${N0}] :: curl installed!\n"
  fi
fi

# not installed
if ! [ -x "$(command -v tor)" ]; then
  printf '%b' "[${GR}!!${N0}] :: Installing tor!\n"
  sudo apt-get install tor -y
  if [ $? -eq 0 ]; then
    printf '%b' "[${G1}OK${N0}] :: tor installed!\n"
  fi
fi

# not installed
if ! [ -x "$(command -v html2text)" ]; then
  printf '%b' "[${GR}!!${N0}] :: Installing html2text!\n"
  sudo apt-get install html2text -y
  if [ $? -eq 0 ]; then
    printf '%b' "[${G1}OK${N0}] :: html2text installed!\n"
  fi
fi

# not installed
if ! [ -x "$(command -v dialog)" ]; then
  printf '%b' "[${GR}!!${N0}] :: Installing dialog!\n"
  sudo apt-get install dialog -y
  if [ $? -eq 0 ]; then
    printf '%b' "[${G1}OK${N0}] :: dialog installed!\n"
  fi
fi

# not installed
if [[ ! "$(arp-scan --version)" ]] &>/dev/null; then
  printf '%b' "[${GR}!!${N0}] :: Installing arp-scan!\n"
  sudo apt-get install arp-scan -y
  if [ $? -eq 0 ]; then
    printf '%b' "[${G1}OK${N0}] :: arp-scan installed!\n"
  fi
fi

################################################################################
# run setup
################################################################################

bash /etc/freedom-node/include/setup

# END
