#!/bin/bash

################################################################################

# colors
B0='\e[34m'   # Blue
B1='\e[94m'   # Blue light
CY='\e[36m'   # Cyan
C1='\e[96m'   # Cyan light
G0='\e[32m'   # Green
G1='\e[92m'   # Green light
GR='\e[90m'   # Grey
N0='\033[0m'  # No color
P0='\e[0;35m' # Purple
P1='\e[1;35m' # Purple light
R0='\e[31m'   # Red
R1='\e[91m'   # Red light
Y0='\e[33m'   # Yellow
Y1='\e[93m'   # Yellow light
BLD='\e[1m'   # Bold\brighter

################################################################################

clear
printf '%b' "${Y0}${BLD}
F   R   E   E   D   O   M   C   O   I   N${B1}

@${N0}@${B1}@${N0}  @${B1}@${N0}@${B1}    @${N0}@${B1}@${N0}@${B1}@${N0}@${B1}    @${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@${N0}    @${B1}@${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@${N0}
${B1}@${N0}@${B1}@${N0}@${B1} @${N0}@${B1}@${N0}   @${B1}@${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@   ${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@   ${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@${N0}@${B1}@${N0}
${N0}@${B1}@${N0}!${B1}@${N0}!${B1}@${N0}@${B1}@   ${N0}@${B1}@${N0}!  ${B1}@${N0}@${B1}@   ${N0}@${B1}@${N0}!  ${B1}@${N0}@${B1}@   ${N0}@${B1}@${N0}!
!@!!@!@!   !@!  @!@   !@!  @!@   !@!${R1}
@!@ !!@!   @!@  !@!   @!@  !@!   @!!!:!${N0}
!@!  !!!   !@!  !!!   !@!  !!!   !!!!!:${R1}
!!:  !!!   !!:  !!!   !!:  !!!   !!:${N0}
:!:  !:!   :!:  !:!   :!:  !:!   :!:${R1}
::   ::    :::: ::    :::: ::    :: ::::${N0}
::    :     : :  :    :: :  :    : :: ::${R1}

${GR}The original TrumpCoin!${N0}

Installing Freedom node! ${GR}Version 2${N0}
\n"

################################################################################
# repository updates
################################################################################

# any updates
printf '%b' "[  ${N0}!!${N0}  ] Updating freedom-node repository..\n"
printf '%b' "[  ${G1}OK${N0}  ] $(cd || exit && cd freedom-node && git pull)\n"

################################################################################
# freedom-node directory & user
################################################################################

# if missing
if [[ ! -d /etc/freedom-node ]] &>/dev/null; then
  printf '%b' "[  ${N0}!!${N0}  ] Creating freedom-node directory..\n"
fi

# create install directory
sudo mkdir /etc/freedom-node &>/dev/null
# fix ownership for freedom-node (whoami)
sudo chown -R "$(whoami)":"$(whoami)" /etc/freedom-node/ 2>/dev/null

# if missing
if [[ ! -f /etc/freedom-node/config ]] &>/dev/null; then
  # create configuration file
  echo "# freedom-node configuration
WALLET_PASSPHRASE="" # walletpassphrase
# set touch device (change to the correct device path)
TOUCH_DEVICE="/dev/input/event0" # <-- replace with your actual touchscreen device" >/etc/freedom-node/config
  printf '%b' "[  ${N0}!!${N0}  ] Creating freedom-node configuration..\n"
fi

# fetch user
echo "$(whoami)" >/etc/freedom-node/user
# user name
USER_NAME="$(cat /etc/freedom-node/user 2>/dev/null)"
printf '%b' "[  ${G1}OK${N0}  ] USER_NAME=${G1}$USER_NAME${N0}\n" && sleep 1

# fetch home directory
echo "$HOME" >/etc/freedom-node/homedir
# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"
printf '%b' "[  ${G1}OK${N0}  ] HOME_DIR=${G1}$HOME_DIR${N0}\n" && sleep 1

################################################################################
# .trumpcoin directory
################################################################################

# if missing
if [[ ! -d "$HOME"/.trumpcoin ]] &>/dev/null; then
  printf '%b' "[  ${N0}!!${N0}  ] Creating .trumpcoin directory..\n"
  # create wallet directory
  mkdir "$HOME"/.trumpcoin &>/dev/null
fi

# fix ownership for trumpcoin
sudo chown -R "$USER_NAME":"$USER_NAME" "$HOME_DIR"/.trumpcoin/ 2>/dev/null

################################################################################
# old wallet keys
################################################################################

# if found
if [[ -f "$HOME_DIR"/wallet.dat ]] &>/dev/null; then
  printf '%b' "[  ${N0}!!${N0}  ] Restoring old wallet keys..\n"
  # restore keys
  cp "$HOME_DIR"/wallet.dat "$HOME_DIR"/.trumpcoin
  # backup keys
  mv "$HOME_DIR"/wallet.dat "$HOME_DIR"/wallet.dat.bkp
fi

################################################################################
# wallet configuration
################################################################################

# if missing
if [[ "$(grep -c "rpcuser=" "$HOME_DIR"/.trumpcoin/trumpcoin.conf)" == "0" || ! -f "$HOME_DIR"/.trumpcoin/trumpcoin.conf ]] &>/dev/null; then
  # create configuration
  touch "$HOME_DIR"/.trumpcoin/trumpcoin.conf &>/dev/null
  printf '%b' "[  ${N0}!!${N0}  ] Setup rpcuser and rpcpassword..\n"
  # add random rpc credentials
  echo "
# RPC credentials
rpcuser=$(tr -dc 'a-z' </dev/urandom 2>&1 | head -c 8 2>&1 | rev 2>&1)
rpcpassword=$(tr -dc 'a-z' </dev/urandom 2>&1 | head -c 8 2>&1 | rev 2>&1)
rpcallowip=127.0.0.1
rpcbind=127.0.0.1" >>"$HOME_DIR"/.trumpcoin/trumpcoin.conf
fi

################################################################################
# install files & create executable
################################################################################

# install freedom-node files
cd || exit && cp -rf freedom-node/include /etc/freedom-node
# create executable file
chmod +x "$USER_NAME":"$USER_NAME" /etc/freedom-node/include/start 2>/dev/null

################################################################################
# requirements
################################################################################

# not installed
if ! [ -x "$(command -v bc)" ]; then
  printf '%b' "[  ${GR}!!${N0}  ] Installing bc!\n"
  sudo apt-get install bc -y
  if [ $? == 0 ]; then
    printf '%b' "[  ${G1}OK${N0}  ] bc installed!\n"
  fi
fi

# not installed
if ! [ -x "$(command -v jq)" ]; then
  printf '%b' "[  ${GR}!!${N0}  ] Installing jq!\n"
  sudo apt-get install jq -y
  if [ $? == 0 ]; then
    printf '%b' "[  ${G1}OK${N0}  ] jq installed!\n"
  fi
fi

# not installed
if ! [ -x "$(command -v ifconfig)" ]; then
  printf '%b' "[  ${GR}!!${N0}  ] Installing net-tools!\n"
  sudo apt-get install net-tools -y
  if [ $? == 0 ]; then
    printf '%b' "[  ${G1}OK${N0}  ] net-tools installed!\n"
  fi
fi

# not installed
if [[ ! "$(curl --version)" ]] &>/dev/null; then
  printf '%b' "[  ${GR}!!${N0}  ] Installing curl!\n"
  sudo apt-get install curl -y
  if [ $? == 0 ]; then
    printf '%b' "[  ${G1}OK${N0}  ] curl installed!\n"
  fi
fi

# not installed
if ! [ -x "$(command -v tor)" ]; then
  printf '%b' "[  ${GR}!!${N0}  ] Installing tor!\n"
  sudo apt-get install tor -y
  if [ $? == 0 ]; then
    printf '%b' "[  ${G1}OK${N0}  ] tor installed!\n"
  fi
fi

# not installed
if ! [ -x "$(command -v html2text)" ]; then
  printf '%b' "[  ${GR}!!${N0}  ] Installing html2text!\n"
  sudo apt-get install html2text -y
  if [ $? == 0 ]; then
    printf '%b' "[  ${G1}OK${N0}  ] html2text installed!\n"
  fi
fi

# not installed
if ! [ -x "$(command -v dialog)" ]; then
  printf '%b' "[  ${GR}!!${N0}  ] Installing dialog!\n"
  sudo apt-get install dialog -y
  if [ $? == 0 ]; then
    printf '%b' "[  ${G1}OK${N0}  ] dialog installed!\n"
  fi
fi

# not installed
if [[ ! "$(arp-scan --version)" ]] &>/dev/null; then
  printf '%b' "[  ${GR}!!${N0}  ] Installing arp-scan!\n"
  sudo apt-get install arp-scan -y
  if [ $? == 0 ]; then
    printf '%b' "[  ${G1}OK${N0}  ] arp-scan installed!\n"
  fi
fi

################################################################################
# run setup
################################################################################

bash /etc/freedom-node/include/setup

# END
