#!/bin/bash

# real event device
DEVICE="/dev/input/event0"

# evtest device
evtest "$DEVICE" | while read -r LINE; do
  if [[ "$LINE" == *"ABS_X"* ]] &>/dev/null; then
    x=$(echo "$LINE" | grep -oP 'value \K[0-9]+')
  elif [[ "$LINE" == *"ABS_Y"* ]] &>/dev/null; then
    y=$(echo "$LINE" | grep -oP 'value \K[0-9]+')
    echo "$x $y" >/tmp/touchcoords
    bash /etc/freedom-node/include/touch &
  fi
done

# END
