#!/bin/bash

# Real event device
DEVICE="/dev/input/event0"
# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

# ensure the directory exists
mkdir -p "$HOME_DIR"/node

# evtest device
evtest "$DEVICE" | while read -r LINE; do
  # capture ABS_X (X coordinate)
  if [[ "$LINE" == *"ABS_X"* ]] &>/dev/null; then
    x=$(echo "$LINE" | grep -v "value 0" | grep -oP 'value \K[0-9]+')
  # capture ABS_Y (Y coordinate)
  elif [[ "$LINE" == *"ABS_Y"* ]] &>/dev/null; then
    y=$(echo "$LINE" | grep -v "value 0" | grep -oP 'value \K[0-9]+')
    # write the coordinates (appending to touchcoords.tmp)
    echo "$x $y" >"$HOME_DIR"/node/touchcoords.tmp
    # capture ABS_PRESSURE (pressure value)
    pressure=$(echo "$LINE" | grep -v "value 0" | grep -oP 'value \K[0-9]+')
  # capture BTN_TOUCH (touch down or up)
  elif [[ "$LINE" == *"BTN_TOUCH"* ]] &>/dev/null; then
    touch_status=$(echo "$LINE" | grep -v "value 0" | grep -oP 'value \K[0-9]+')

    # ensure that pressure is correctly assigned
    if [ -z "$pressure" ]; then
      pressure=0 # default to 0 if no pressure value is found
    fi

    # get (format: Touch:x:y:pressure:touch_status)
    echo "Touch:$x:$y:$pressure:$touch_status" >"$HOME_DIR"/node/touchconfig.tmp
    # restart the touch process
    pkill -f /etc/freedom-node/include/touch
    bash /etc/freedom-node/include/touch &
  fi
done

# END
