#!/bin/bash

################################################################################

source /etc/freedom-node/include/color

################################################################################

HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

################################################################################
# freedomcoin client & daemon
################################################################################

# stop daemon with client
/usr/local/bin/freedomcoin-cli stop
sleep 1
# start daemon
bash /etc/freedom-node/include/start

# END
