#!/bin/bash

################################################################################

source /etc/freedom-node/include/color

################################################################################

# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"
# user
USER_NAME="$(cat /etc/freedom-node/user 2>/dev/null)"

################################################################################
# model & cpu info
################################################################################

VER_FOUND="$(uname -v)"
REL_FOUND="$(uname -r)"
MOD_FOUND="$(grep "Model" /proc/cpuinfo | awk -F: '{ print $2 }' | xargs)"

# if zero
if [[ -z "$MOD_FOUND" ]] &>/dev/null; then
  MOD_FOUND="$(grep "vendor_id" /proc/cpuinfo | awk -F: '{ print $2 }' | head -1 | xargs)"
fi

CPU_FOUND="$(grep "model name" /proc/cpuinfo | head -1 | awk -F: '{ print $2 }' | xargs)"

# if zero
if [[ -z "$CPU_FOUND" ]] &>/dev/null; then
  CPU_FOUND="$(lscpu | grep "Model name" | awk -F: '{ print $2 }' | xargs)"
fi

MHZ_FOUND="$(echo "$(lscpu | grep "MHz" | awk -F: '{ print $2 }' | grep -v "%" | head -1 | awk '{ print $1 }')/1000" | bc -l 2>/dev/null | awk '{ printf "%.2f\n", $1 }') GHz"

# if zero
if [[ -z "$MHZ_FOUND" ]] &>/dev/null; then
  MHZ_FOUND=""
else
  MHZ_FOUND="${CY}$MHZ_FOUND${N0}"
fi

################################################################################
# system info
################################################################################

BOG_FOUND="$(egrep "bogomips|BogoMIPS" /proc/cpuinfo | awk '{ print $NF }' | head -1)"
COR_FOUND="$(egrep -c "bogomips|BogoMIPS" /proc/cpuinfo)"
MEM_FOUND="$(echo "$(echo "$(grep "MemTotal" /proc/meminfo | awk '{ print $2 }')+"$(grep "SwapTotal" /proc/meminfo | awk '{ print $2 }') | bc -l 2>/dev/null)/1024" | bc 2>/dev/null) MB"
HDD_FOUND="$(df -h --total | tail -1 | xargs | tr -d '-')"
HDD_TOTAL="$(echo "$HDD_FOUND" | awk '{ print $2 }')"
HDD_FREE="$(echo "$HDD_FOUND" | awk '{ print $4 }')"

echo "$MEM_FOUND" >/tmp/mem.tmp

################################################################################
# bogomips
################################################################################

# if found
if [[ -n "$BOG_FOUND" ]] &>/dev/null; then
  printf '%b' "[  ${G1}OK${N0}  ] BogoMIPS: ${CY}$BOG_FOUND${N0}\n"
else
  printf '%b' "[  ${GR}!!${N0}  ] Error\n" && exit
fi

################################################################################
# kernal release version
################################################################################

# if found
if [[ -n "$VER_FOUND" ]] &>/dev/null; then
  printf '%b' "[  ${G1}OK${N0}  ] $VER_FOUND\n"
else
  printf '%b' "[  ${GR}!!${N0}  ] Error\n" && exit
fi

# if found
if [[ -n "$REL_FOUND" ]] &>/dev/null; then
  printf '%b' "[  ${G1}OK${N0}  ] $REL_FOUND\n"
else
  printf '%b' "[  ${GR}!!${N0}  ] Error\n" && exit
fi

################################################################################
# model
################################################################################

# if found
if [[ -n "$MOD_FOUND" ]] &>/dev/null; then
  printf '%b' "[  ${G1}OK${N0}  ] $MOD_FOUND\n"
else
  printf '%b' "[  ${GR}!!${N0}  ] ${GR}Not found${N0}\n"
fi

################################################################################
# cpu
################################################################################

# if found
if [[ -n "$CPU_FOUND" ]] &>/dev/null; then
  printf '%b' "[  ${G1}OK${N0}  ] $CPU_FOUND $COR_FOUND Core(s) $MHZ_FOUND\n"
else
  printf '%b' "[  ${GR}!!${N0}  ] Error\n" && exit
fi

################################################################################
# memory
################################################################################

# if found
if [[ -n "$MEM_FOUND" ]] &>/dev/null; then
  printf '%b' "[  ${G1}OK${N0}  ] $MEM_FOUND\n"
  # if not enough memory
  if [[ "$(echo "$MEM_FOUND" | awk '{ print $1 }')" -lt "2000" ]] &>/dev/null; then
    printf '%b' "[  ${GR}!!${N0}  ] Not enough memory!\n" && sleep 1
    if [[ "$(echo "$HDD_FREE" | tr -d 'G')" -gt "7" ]] &>/dev/null; then
      printf '%b' "[  ${G1}OK${N0}  ] Creating 2G Swap..\n"
      # create 2G swap #########################################################
      sudo fallocate -l 2G /swapfile
      sudo chmod 600 /swapfile
      sudo mkswap /swapfile
      sudo swapon /swapfile
      ##########################################################################
      # if swapfile is not already in /etc/fstab, append it
      if ! grep -q "^/swapfile swap swap defaults 0 0" /etc/fstab; then
        printf '%b' "[  ${G1}OK${N0}  ] Updating fstab..\n"
        echo "/swapfile swap swap defaults 0 0" | sudo tee -a /etc/fstab >/dev/null
      fi
    else
      printf '%b' "[  ${GR}!!${N0}  ] Not enough space for Swap! ${R1}$HDD_FREE${N0}\n" && sleep 1
    fi
  fi
else
  printf '%b' "[  ${GR}!!${N0}  ] Swap Error\n" && exit
fi

################################################################################
# hard drive
################################################################################

# if found
if [[ -n "$HDD_FOUND" ]] &>/dev/null; then
  printf '%b' "[  ${G1}OK${N0}  ] Total $HDD_TOTAL Free $HDD_FREE\n"
  # if not enough space
  if [[ "$(echo "$HDD_FREE" | tr -d 'G')" -lt "7" ]] &>/dev/null; then
    printf '%b' "[  ${GR}!!${N0}  ] Not enough space..\n" && exit
  fi
  # if tiny sd card found
  if [[ "$(echo "$HDD_TOTAL" | tr -d 'G')" -lt "32" ]] &>/dev/null; then
    printf '%b' "[  ${GR}!!${N0}  ] 32GB SD card recommended.\n" && exit
  fi
else
  printf '%b' "[  ${GR}!!${N0}  ] Error\n" && exit
fi

################################################################################
# missing wallet daemon or client
################################################################################

# if VPS already, skip this
if [[ -d "$HOME_DIR"/freed1 || -d "$HOME_DIR"/trump1 ]] &>/dev/null; then
  echo "[  !!  ] This is a VPS Server already with $(pidof freedomcoind 2>/dev/null | wc -w) nodes running.."
  # remove obsolete dash for vps server
  sudo rm /usr/local/bin/dash &>/dev/null

else

  # wallet exist
  if [[ -f "$HOME"/freedomcoind && -f "$HOME"/freedomcoin-cli ]] &>/dev/null; then
    # install wallet
    sudo cp "$HOME"/freedomcoin* /usr/local/bin
    sudo chown "$USER_NAME":"$USER_NAME" /usr/local/bin/freedomcoin*
  fi

  # download wallet
  bash /etc/freedom-node/include/download

  ##############################################################################
  # wallet configuration
  ##############################################################################

  # if missing
  if [[ "$(grep -c "rpcuser=" "$HOME_DIR"/.trumpcoin/trumpcoin.conf)" -eq "0" || ! -f "$HOME_DIR"/.trumpcoin/trumpcoin.conf ]] &>/dev/null; then
    printf '%b' "[  ${N0}!!${N0}  ] Setup rpcuser and rpcpassword..\n"
    # add random rpc credentials
    echo "
# RPC credentials
rpcuser=$(tr -dc 'a-z' </dev/urandom 2>&1 | head -c 8 2>&1 | rev 2>&1)
rpcpassword=$(tr -dc 'a-z' </dev/urandom 2>&1 | head -c 8 2>&1 | rev 2>&1)
rpcallowip=127.0.0.1
rpcbind=127.0.0.1" >>"$HOME_DIR"/.trumpcoin/trumpcoin.conf
  fi

  ##############################################################################
  # dashbord (dash)
  ##############################################################################

  # install dash
  cd || exit && sudo cp freedom-node/dash /usr/local/bin
  sudo chmod +x "$USER_NAME":"$USER_NAME" /usr/local/bin/dash 2>/dev/null
  sudo chown "$USER_NAME":"$USER_NAME" /usr/local/bin/dash 2>/dev/null

  ##############################################################################
  # proxy (tor) configuration
  ##############################################################################

  # if missing
  if [[ "$(grep -c "FreedomCoin-service" /etc/tor/torrc)" -eq "0" ]] &>/dev/null; then
    # update tor configuration
    printf '%b' "[  ${GR}!!${N0}  ] Updating configuration!\n"
    echo "HiddenServiceDir /var/lib/tor/FreedomCoin-service/
HiddenServicePort 15110 127.0.0.1:15110" | sudo tee -a /etc/tor/torrc >/dev/null
    # update tor configuration
    printf '%b' "[  ${GR}!!${N0}  ] Restarting tor!\n"
    sudo service tor@default restart
  fi

  ##############################################################################
  # network interface
  ##############################################################################

  # fetch lan from ifconfig
  ifconfig | grep "inet" | egrep -v "prefix|127" | awk '{ print $2 }' >/tmp/lanip.tmp
  printf '%b' "[  ${G1}OK${N0}  ] ${N0}$(cat /tmp/lanip.tmp 2>/dev/null)${N0}\n"
  # fetch wan from whatismyip
  curl -s http://whatismyip.akamai.com/ >/tmp/wanip.tmp
  printf '%b' "[  ${G1}OK${N0}  ] ${CY}$(cat /tmp/wanip.tmp 2>/dev/null)${N0}\n"
  # fetch onion from hidden service
  sudo cat /var/lib/tor/FreedomCoin-service/hostname >/etc/freedom-node/hostname.onion
  printf '%b' "[  ${G1}OK${N0}  ] ${P1}$(cat /etc/freedom-node/hostname.onion 2>/dev/null)${N0}\n"

  ##############################################################################
  # bootstrap
  ##############################################################################

  bash /etc/freedom-node/include/bootstrap

  ##############################################################################
  # freedomcoin daemon service
  ##############################################################################

  # if missing
  if [[ ! -f /etc/systemd/system/freedomcoind.service ]] &>/dev/null; then

    echo "[Unit]
  Description=freedomcoind service
  After=network-online.target

  [Service]
  Type=simple
  User=$USER_NAME
  Group=$USER_NAME
  ExecStart=/etc/freedom-node/include/start
  ExecReload=/etc/freedom-node/include/restart
  ExecStop=/usr/local/bin/freedomcoin-cli stop
  Restart=always
  RestartSec=60

  [Install]
  WantedBy=multi-user.target" >/tmp/service.tmp

    # install service
    sudo mv /tmp/service.tmp /etc/systemd/system/freedomcoind.service &>/dev/null
    # enable service
    printf '%b' "[  ${G1}OK${N0}  ] Enabling FreedomCoin service..\n"
    sudo systemctl daemon-reload
    sudo systemctl enable freedomcoind
  fi

  ##############################################################################
  # freedomcoin display service
  ##############################################################################

  # touchscreen?
  if [ ! -z "$(dmesg | grep 'touchscreen')" ]; then
    printf '%b' "[  ${G1}OK${N0}  ] Touchscreen detected! (high probability to be a TFT/LCD screen)\n"
    # display detected
    DISPLAY_DETECTED="1"
  fi

  # second framebuffer?
  if [ -d "/sys/class/graphics/fb1" ]; then
    printf '%b' "[  ${G1}OK${N0}  ] Secondary framebuffer found! (TFT/LCD screen would be fb1, unless more than one monitor)\n"
    # display detected
    DISPLAY_DETECTED="1"
  fi

  # check if display is connected
  if [[ "$DISPLAY_DETECTED" == "1" ]] &>/dev/null; then
    printf '%b' "[  ${G1}OK${N0}  ] Display detected. ${CY}$(cat /sys/class/graphics/fb0/virtual_size 2>/dev/null | tr ',' 'x')${N0}\n"

    # if service doesn't exist, create it
    if [[ ! -f /etc/systemd/system/freedomnode.service ]] &>/dev/null; then

      cat <<EOF >/tmp/service.tmp
[Unit]
Description=FreedomNode Startup Script
After=network.target

[Service]
Type=simple
User=$USER_NAME
WorkingDirectory=/home/freedom/freedom-node
ExecStart=/bin/bash /home/freedom/freedom-node/dash.sh
StandardOutput=inherit
StandardError=inherit
Restart=always

[Install]
WantedBy=multi-user.target
EOF

      # install service
      sudo mv /tmp/service.tmp /etc/systemd/system/freedomnode.service
      printf '%b' "[  ${G1}OK${N0}  ] Enabling display service..\n"
      # apply service + disable getty on tty1
      sudo systemctl daemon-reexec
      sudo systemctl daemon-reload
      sudo systemctl enable freedomnode.service
      sudo systemctl start freedomnode.service
    fi
  fi

  ##############################################################################
  # freedomcoin start
  ##############################################################################

  # daemon running
  if [[ "$(pidof freedomcoind 2>/dev/null | wc -l)" -gt "0" ]] &>/dev/null; then
    printf '%b' "[  ${G1}OK${N0}  ] Already running! PID: ${G1}$(pidof freedomcoind)${N0}\n"
    printf '%b' "[  ${G1}OK${N0}  ] Run ${CY}dash${N0} and monitor!\n"
  else
    # start service
    sudo service freedomcoind restart
  fi
fi

# END
