#!/bin/bash

################################################################################

for (( ; ; )); do # loop dashbord

  source /etc/freedom-node/include/color

  ##############################################################################

  HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

  ##############################################################################

  sync_check() {
    # sync check
    /usr/local/bin/./freedomcoind getblockchaininfo | head -20 >/tmp/gbci.tmp
    GET_BLOCKCHAIN_INFO="$(</tmp/gbci.tmp)"
    BLOCKS="$(echo "$GET_BLOCKCHAIN_INFO" | tr -d '",' | grep "blocks:" | awk '{ print $NF }')"
    HEADERS="$(echo "$GET_BLOCKCHAIN_INFO" | tr -d '",' | grep "headers:" | awk '{ print $NF }')"
    DOWNLOADING_BLOCK="$(echo "$GET_BLOCKCHAIN_INFO" | tr -d '",' | grep "initial_block_downloading:" | awk '{ print $NF }')"
    # synced but still downloading
    if [[ "$BLOCKS" == "$HEADERS" && "$DOWNLOADING_BLOCK" == "true" ]]; then
      # stop wallet
      /usr/local/bin/./freedomcoin-cli stop
    fi
  }

  ##############################################################################
  # freedomcoin daemon
  ##############################################################################

  # daemon not running
  if ! pgrep -x freedomcoind >/dev/null; then
    # client exist
    if [[ -f /usr/local/bin/freedomcoin-cli ]] &>/dev/null; then
      sync_check
    fi
    # daemon exist
    if [[ -f /usr/local/bin/freedomcoind ]] &>/dev/null; then
      # reset old log
      truncate -s 0 "$HOME"/.trumpcoin/debug.log &>/dev/null
      # remove old data files
      rm "$HOME"/node/*.tmp &>/dev/null
      # output daemon
      printf '%b' "[  ${G1}OK${N0}  ] Daemon  : "
      # start daemon
      /usr/local/bin/./freedomcoind -datadir="$HOME_DIR/.trumpcoin" -debuglogfile="$HOME_DIR/.trumpcoin/debug.log" -conf="$HOME_DIR/.trumpcoin/trumpcoin.conf" -debug="tor" -proxy="127.0.0.1:9050" -daemon
    fi
  fi
  sleep 60
done

# END
