#!/bin/bash

################################################################################
# time (loop) w time fix (correction)
################################################################################

TIME="60" # loop every n second

# shellcheck disable=SC2034  # Unused variables left for readability

# after the fact (script), remove leading zero
TIME_SECONDS="$(date +"%S" | sed 's/^0*//g; s/\.0*/./g' 2>/dev/null)"
if [ -z "$TIME_SECONDS" ] &>/dev/null; then
  # too many zeros, create fiction
  TIME_SECONDS="1"
fi
if [[ "$TIME_SECONDS" -gt "30" ]] &>/dev/null; then
  # wait extra n seconds
  TIME_FIX=$(echo "${TIME:?}-${TIME_SECONDS:?}" | bc -l 2>/dev/null)
  TIME=$(echo "${TIME:?}+${TIME_FIX:?}" | bc -l 2>/dev/null)
else
  # wait less n seconds
  TIME=$(echo "${TIME:?}-${TIME_SECONDS:?}" | bc -l 2>/dev/null)
fi

# END
