#!/bin/bash

# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

# define touch zones in raw touchscreen coordinates (based on evtest)
ZONES=(
  "Peers:2200:2700:2700:3100"   # Wallet connections
  "Balance:2000:1300:2400:1700" # Wallet balances
  "System:3100:1300:3300:1700"  # System information
)

# if any data
if [[ -f /tmp/touchcoords ]] &>/dev/null; then
  # get last touch coordinates from tmp file (evtest listener should write here)
  read -r x y </tmp/touchcoords || exit 0

  handle_zone() {
    case "$1" in
    Peers)
      WALLET_PEERS_INFO="$(cat "$HOME_DIR"/node/getpeerinfo.tmp 2>/dev/null | tr -d '",' | grep "addr:" | grep -v "get" | awk '{ print $2 }' | sort)"
      # if zero
      if [[ -z "$WALLET_PEERS_INFO" ]] &>/dev/null; then
        WALLET_PEERS_INFO="No peers.."
        dialog --infobox "$WALLET_PEERS_INFO" 4 16
      else
        dialog --infobox "$WALLET_PEERS_INFO" 0 0
      fi
      ;;
    Balance)
      WALLET_BALANCES_INFO="$(cat "$HOME_DIR"/node/getwalletinfo.tmp 2>/dev/null | grep "balance" | tr -d ' ,"' | tr ':' ' ' | column -t | tr '_' ' ')"
      # if zero
      if [[ -z "$WALLET_BALANCES_INFO" ]] &>/dev/null; then
        WALLET_BALANCES_INFO="No balances"
        dialog --infobox "$WALLET_BALANCES_INFO" 4 16
      else
        dialog --infobox "$WALLET_BALANCES_INFO" 0 0
      fi
      ;;
    Internet)
      WALLET_INTERNET_INFO="LAN   : $(cat "$HOME_DIR"/node/lanip 2>/dev/null)
WAN   : $(cat "$HOME_DIR"/node/wanip 2>/dev/null)
Onion : $(cat "$HOME_DIR"/node/onionip 2>/dev/null)"
      # if zero
      if [[ -z "$WALLET_INTERNET_INFO" ]] &>/dev/null; then
        WALLET_INTERNET_INFO="No network.."
        dialog --infobox "$WALLET_INTERNET_INFO" 4 16

      else
        dialog --infobox "$WALLET_INTERNET_INFO" 0 0
      fi
      ;;
    Network)
      dialog --infobox "$(ifconfig | grep -v "127" | grep -A7 "inet " | grep -v "flags" | egrep "inet |netmask|broadcast" | xargs | tr ' ' '\n')" 0 0
      ;;
    M)
      dialog --infobox "Masternode information" 0 0
      ;;
    D)
      dialog --infobox "Dark theme enabled." 0 0
      ;;
    Staking)
      dialog --infobox "Staking status" 0 0
      ;;
    Proxy)
      dialog --infobox "Proxy status" 0 0
      ;;
    System)
      # if missing
      if [[ ! -f "$HOME_DIR"/node/hostnamectl ]] &>/dev/null; then
        echo "$(hostnamectl)" >"$HOME_DIR"/node/hostnamectl
      fi
      WALLET_SYSTEM_INFO="$(cat "$HOME_DIR"/node/hostnamectl 2>/dev/null)"
      # if zero
      if [[ -z "$WALLET_SYSTEM_INFO" ]] &>/dev/null; then
        WALLET_SYSTEM_INFO="No system info"
        dialog --infobox "$WALLET_SYSTEM_INFO" 4 19
      fi
      dialog --infobox "$WALLET_SYSTEM_INFO" 0 0
      ;;
    FreeMem)
      dialog --infobox "$(ifconfig | grep -v "127" | grep -A7 "inet " | grep -v "flags" | egrep "inet |netmask|broadcast" | xargs | tr ' ' '\n')" 0 0
      ;;
    HDDuse)
      dialog --infobox "$(df -h)" 0 0
      ;;
    esac
  }

  # check if the touch falls inside a zone
  for ZONE in "${ZONES[@]}"; do
    IFS=":" read -r LABEL x1 y1 x2 y2 <<<"$ZONE"
    if ((x >= x1 && x <= x2 && y >= y1 && y <= y2)); then
      # handle zone label (display dialog)
      handle_zone "$LABEL"
    fi
    clear
  done
fi

# END
