#!/bin/bash

source /etc/freedom-node/include/time_fix

exec 2>/dev/null
# restore terminal to sane state
trap 'sleep '"${TIME:?}"'; reset; stty sane; clear; tput rmcup' EXIT

# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

# define touch zones in raw touchscreen coordinates (based on evtest)
ZONES=(
  "Peers:2200:2700:2700:3100"    # Wallet connections
  "Balance:2000:1300:2400:1700"  # Wallet balances
  "System:3100:1300:3300:1700"   # System information
  "Network:3350:3620:3500:3760"  # Network information
  "Internet:2400:1350:2550:1450" # Internet information
)

# if any data
if [[ -f /tmp/touchcoords ]] &>/dev/null; then
  # get last touch coordinates from tmp file (evtest listener should write here)
  read -r x y </tmp/touchcoords || exit 0

  handle_zone() {
    case "$1" in
    Peers)
      WALLET_PEERS_INFO="$(cat "$HOME_DIR"/node/getpeerinfo.tmp 2>/dev/null | tr -d '",' | grep "addr:" | grep -v "get" | awk '{ print $2 }' | sort)"
      # if zero
      if [[ -z "$WALLET_PEERS_INFO" ]] &>/dev/null; then
        WALLET_PEERS_INFO="No peers.."
        dialog --infobox "$WALLET_PEERS_INFO" 4 16
      else
        dialog --infobox "$WALLET_PEERS_INFO" 0 0
      fi
      ;;
    Balance)
      WALLET_BALANCES_INFO="$(cat "$HOME_DIR"/node/getwalletinfo.tmp 2>/dev/null | grep "balance" | tr -d ' ,"' | tr ':' ' ' | column -t | tr '_' ' ')"
      # if zero
      if [[ -z "$WALLET_BALANCES_INFO" ]] &>/dev/null; then
        WALLET_BALANCES_INFO="No balances"
        dialog --infobox "$WALLET_BALANCES_INFO" 4 16
      else
        dialog --no-collapse --infobox "$WALLET_BALANCES_INFO" 0 0
      fi
      ;;
    Internet)
      WALLET_INTERNET_INFO="LAN   : $(cat "$HOME_DIR"/node/lanip 2>/dev/null)
WAN   : $(cat "$HOME_DIR"/node/wanip 2>/dev/null)
Onion : $(cat "$HOME_DIR"/node/onionip 2>/dev/null)"
      # if zero
      if [[ -z "$WALLET_INTERNET_INFO" ]] &>/dev/null; then
        WALLET_INTERNET_INFO="No network.."
        dialog --infobox "$WALLET_INTERNET_INFO" 4 16
      else
        dialog --no-collapse --infobox "$(echo "$WALLET_INTERNET_INFO" | column -t)" 4 16
      fi
      ;;
    Network)
      echo "$(ifconfig 2>/dev/null)" >/tmp/ifconfig
      WALLET_NETWORK_INFO="Address: $(grep -v "127" /tmp/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $2 }')
Netmask: $(grep -v "127" /tmp/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $4 }')
Broadcast: $(grep -v "127" /tmp/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $6 }')"
      dialog --no-collapse --infobox "$(echo "$WALLET_NETWORK_INFO" | column -t)" 0 0
      ;;
    M)
      dialog --infobox "Masternode information" 0 0
      ;;
    D)
      dialog --infobox "Dark theme enabled." 0 0
      ;;
    Staking)
      dialog --infobox "Staking status" 0 0
      ;;
    Proxy)
      dialog --infobox "Proxy status" 0 0
      ;;
    System)
      # if missing
      if [[ ! -f "$HOME_DIR"/node/hostnamectl ]] &>/dev/null; then
        echo "$(hostnamectl)" >"$HOME_DIR"/node/hostnamectl
      fi
      WALLET_SYSTEM_INFO="$(cat "$HOME_DIR"/node/hostnamectl 2>/dev/null)"
      # if zero
      if [[ -z "$WALLET_SYSTEM_INFO" ]] &>/dev/null; then
        WALLET_SYSTEM_INFO="No system info"
        dialog --infobox "$WALLET_SYSTEM_INFO" 4 19
      fi
      dialog --infobox "$WALLET_SYSTEM_INFO" 0 0
      ;;
    FreeMem)
      dialog --no-collapse --infobox "$(echo "$(free -tm | awk '{ print $1,$2,$3,$4 }')" | column -t)" 0 0
      ;;
    HDDuse)
      dialog --infobox "$(df -h)" 0 0
      ;;
    esac
  }

  # check if the touch falls inside a zone
  for ZONE in "${ZONES[@]}"; do
    IFS=":" read -r LABEL x1 y1 x2 y2 <<<"$ZONE"
    if ((x >= x1 && x <= x2 && y >= y1 && y <= y2)); then
      # handle zone label (display dialog)
      handle_zone "$LABEL"
    fi
  done
fi

# END
