#!/bin/bash

source /etc/freedom-node/include/time_fix

exec 2>/dev/null
# restore terminal to sane state
trap 'sleep '"${TIME:?}"'; reset; stty sane; clear; tput rmcup' EXIT

# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

################################################################################

# define touch zones in raw touchscreen coordinates (based on evtest)
ZONES=(
  "Node:3635:341:3751:392"          # node information
  "Stats:3596:750:3857:899"         # stats
  "PoS:3677:1175:3842:1323"         # proof of stake
  "Patriotnode:3673:1793:3858:1942" # patriotnode
  "Update:3422:2459:3804:2675"      # repo update
  "Upgrade:3169:2872:3791:3255"     # system upgrade
  "System:3723:348:3761:383"        # system information
  "Balances:1980:1580:1920:1620"    # balances
  "Internet:2289:1324:2442:1467"    # internet
  "Intranet:3267:3701:2567:3218"    # intranet
  "Peers:2252:2773:2124:2656"       # connections
)

################################################################################

# if any data
if [[ -f "$HOME_DIR"/node/touchcoords.tmp ]] &>/dev/null; then
  # get last touch coordinates from tmp file (evtest listener should write here)
  read -r x y <"$HOME_DIR"/node/touchcoords.tmp || exit 0

  handle_zone() {
    case "$1" in
    ############################################################################
    Peers)
      WALLET_PEERS_INFO="$(cat /etc/freedom-node/connected.peers 2>/dev/null)"
      # if zero
      if [[ -z "$WALLET_PEERS_INFO" ]] &>/dev/null; then
        WALLET_PEERS_INFO="No peers.."
        dialog --infobox "$WALLET_PEERS_INFO" 4 16
      else
        dialog --infobox "$WALLET_PEERS_INFO" 0 0
      fi
      ;;
      ##########################################################################
    Balances)
      WALLET_BALANCES_INFO="$(cat "$HOME_DIR"/node/getwalletinfo.tmp 2>/dev/null | grep "balance" | tr -d ' ,"' | tr ':' ' ' | column -t | tr '_' ' ')"
      # if zero
      if [[ -z "$WALLET_BALANCES_INFO" ]] &>/dev/null; then
        WALLET_BALANCES_INFO="No balances"
        dialog --infobox "$WALLET_BALANCES_INFO" 4 16
      else
        dialog --no-collapse --infobox "$WALLET_BALANCES_INFO" 0 0
      fi
      ;;
      ##########################################################################
    Internet)
      WALLET_ONION_IP="$(cat "$HOME_DIR"/node/onionip.tmp 2>/dev/null)"
      WALLET_INTERNET_INFO="LAN: $(cat "$HOME_DIR"/node/lanip.tmp 2>/dev/null)
WAN: $(cat "$HOME_DIR"/node/wanip.tmp 2>/dev/null)
TOR: ${WALLET_ONION_IP:0:24}...onion"
      # if zero
      if [[ -z "$WALLET_INTERNET_INFO" ]] &>/dev/null; then
        WALLET_INTERNET_INFO="No network.."
        dialog --infobox "$WALLET_INTERNET_INFO" 4 16
      else
        dialog --no-collapse --infobox "$(echo "$WALLET_INTERNET_INFO" | column -t)" 0 0
      fi
      ;;
      ##########################################################################
    Intranet)
      echo "$(ifconfig 2>/dev/null)" >"$HOME_DIR"/node/ifconfig
      WALLET_NETWORK_INFO="Address: $(grep -v "127" "$HOME_DIR"/node/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $2 }')
Netmask: $(grep -v "127" "$HOME_DIR"/node/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $4 }')
Broadcast: $(grep -v "127" "$HOME_DIR"/node/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $6 }')"
      dialog --no-collapse --infobox "$(echo "$WALLET_NETWORK_INFO" | column -t)" 0 0
      ;;
    System)
      ##########################################################################
      # if missing
      if [[ ! -f "$HOME_DIR"/node/hostnamectl ]] &>/dev/null; then
        echo "$(hostnamectl)" >"$HOME_DIR"/node/hostnamectl
      fi
      WALLET_SYSTEM_INFO="$(cat "$HOME_DIR"/node/hostnamectl 2>/dev/null)"
      # if zero
      if [[ -z "$WALLET_SYSTEM_INFO" ]] &>/dev/null; then
        WALLET_SYSTEM_INFO="No system info"
        dialog --infobox "$WALLET_SYSTEM_INFO" 4 19
      fi
      dialog --no-collapse --infobox "$WALLET_SYSTEM_INFO" 0 0
      ;;
      ##########################################################################
    esac
    exit
  }

  # check if the touch falls inside a zone
  for ZONE in "${ZONES[@]}"; do
    IFS=":" read -r LABEL x1 y1 x2 y2 <<<"$ZONE"
    if ((x >= x1 && x <= x2 && y >= y1 && y <= y2)); then
      # handle zone label (display dialog)
      handle_zone "$LABEL"
    fi
  done
fi

# END
