#!/bin/bash

# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"
# user
USER_NAME="$(cat /etc/freedom-node/user 2>/dev/null)"

################################################################################

# if VPS already, skip this
if [[ -d "$HOME_DIR"/freed1 || -d "$HOME_DIR"/trump1 ]] &>/dev/null; then
  echo "[  !!  ] This is a VPS Server already with $(pgrep -x freedomcoind 2>/dev/null | wc -w) nodes running.."
  exit
fi

# if any data
if [[ -n "$HOME_DIR" && -n "$USER_NAME" ]] &>/dev/null; then
  read -r -p "[  YN  ] Uninstall node! Are you sure? y/n " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]] &>/dev/null; then

    # stop service
    echo "[  !!  ] Stopping service.."
    sudo service freedomcoind stop &>/dev/null
    # disable service
    echo "[  !!  ] Disabling service.."
    sudo systemctl disable freedomcoind &>/dev/null
    # reload units
    sudo systemctl daemon-reload

    # if found
    if [[ -f "$HOME_DIR"/.trumpcoin/wallet.dat ]] &>/dev/null; then
      # backup wallet keys
      printf '%b' "[  !!  ] Backup wallet keys -> \e[92m$HOME_DIR/wallet.dat\033[0m\n"
      cp "$HOME_DIR"/.trumpcoin/wallet.dat "$HOME_DIR" 2>/dev/null
    fi
    # if found
    if [[ -f /etc/systemd/system/freedomcoind.service ]] &>/dev/null; then
      # remove install dir, dash, tmp files
      echo "[  !!  ] Removing old install.."
      sudo rm /etc/systemd/system/freedomcoind.service &>/dev/null
    fi
    # if found
    if [[ -d "$HOME_DIR"/freedom-node ]] &>/dev/null; then
      sudo rm -r "$HOME_DIR"/freedom-node &>/dev/null
    fi
    # if found
    if [[ -d "$HOME_DIR"/.trumpcoin ]] &>/dev/null; then
      sudo rm -r "$HOME_DIR"/.trumpcoin &>/dev/null
    fi
    # if found
    if [[ -f /usr/local/bin/dash ]] &>/dev/null; then
      sudo rm /usr/local/bin/dash &>/dev/null
    fi
    # if found
    if [[ -d /etc/freedom-node ]] &>/dev/null; then
      sudo rm -r /etc/freedom-node &>/dev/null
    fi

    sudo rm -r /home/"$USER_NAME"/node/*.tmp &>/dev/null
    sudo rm -r /home/"$USER_NAME"/node/quotes &>/dev/null

    printf '%b' "[  \e[92mOK\033[0m  ] Done.\n"
  fi
fi

# END
