#!/bin/bash

################################################################################

# real event device
DEVICE="/dev/input/event0"
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

################################################################################

# evemu-record version
evemu-record "$DEVICE" | while read -r LINE; do
  if [[ "$LINE" =~ ABS_X ]]; then
    x=$(echo "$LINE" | awk '{ print $10 }')
  elif [[ "$LINE" =~ ABS_Y ]]; then
    y=$(echo "$LINE" | awk '{ print $10 }')
    # detect any
    if [[ -n "$x" && -n "$y" ]]; then
      htop
    fi
  fi
done

# END
