#!/bin/bash

################################################################################

# real event device
DEVICE="/dev/input/event0"
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

################################################################################

# evemu-record version
evemu-record "$DEVICE" | while read -r LINE; do
  if [[ "$LINE" =~ ABS_X ]] &>/dev/null; then
    x=$(echo "$LINE" | awk '{ print $10 }')
  elif [[ "$LINE" =~ ABS_Y ]] &>/dev/null; then
    y=$(echo "$LINE" | awk '{ print $10 }')
    if [[ -n "$x" && -n "$y" ]] &>/dev/null; then
      echo "false" >/tmp/control_loop.tmp
      bash /etc/freedom-node/include/display/menu
      echo "true" >/tmp/control_loop.tmp
    fi
  fi
done

# END
