#!/bin/bash

################################################################################

# real event device
DEVICE="/dev/input/event0"
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

################################################################################

# evemu-record version
evemu-record "$DEVICE" | while read -r LINE; do
  if [[ "$LINE" =~ ABS_X ]]; then
    x=$(echo "$LINE" | awk '{ print $10 }')
  elif [[ "$LINE" =~ ABS_Y ]]; then
    y=$(echo "$LINE" | awk '{ print $10 }')
    echo "$x $y" >>"$HOME_DIR"/node/touchcoords.tmp
    pkill -f /etc/freedom-node/include/display/touch
    bash /etc/freedom-node/include/display/touch &
  fi
done

# END
