#!/bin/bash

################################################################################

HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

################################################################################

HEIGHT="12"
WIDTH="23"
CHOICE_HEIGHT="5"
BACKTITLE="FreedomCoin Touchscreen Menu"
TITLE="FreedomCoin Menu"
MENU="Choose one option:"

OPTIONS=(1 "Connections"
  2 "Balances"
  3 "Intranet"
  4 "Internet"
  5 "System")

CHOICE=$(dialog --clear \
  --backtitle "$BACKTITLE" \
  --title "$TITLE" \
  --menu "$MENU" \
  $HEIGHT $WIDTH $CHOICE_HEIGHT \
  "${OPTIONS[@]}" \
  2>&1 >/dev/tty)

clear
case $CHOICE in

################################################################################

"1")

  WALLET_PEERS_INFO="$(cat /etc/freedom-node/connected.peers 2>/dev/null)"
  # if zero
  if [[ -z "$WALLET_PEERS_INFO" ]] &>/dev/null; then
    WALLET_PEERS_INFO="No peers.."
    dialog --msgbox "$WALLET_PEERS_INFO" 4 16
  else
    dialog --msgbox "$WALLET_PEERS_INFO" 0 0
  fi

  ;;

################################################################################

"2")

  WALLET_BALANCES_INFO="$(cat "$HOME_DIR"/node/getwalletinfo.tmp 2>/dev/null | grep "balance" | tr -d ' ,"' | tr ':' ' ' | column -t | tr '_' ' ')"
  # if zero
  if [[ -z "$WALLET_BALANCES_INFO" ]] &>/dev/null; then
    WALLET_BALANCES_INFO="No balances"
    dialog --msgbox "$WALLET_BALANCES_INFO" 4 16
  else
    dialog --no-collapse --msgbox "$WALLET_BALANCES_INFO" 0 0
  fi

  ;;

################################################################################

"3")

  echo "$(ifconfig 2>/dev/null)" >"$HOME_DIR"/node/ifconfig
  WALLET_NETWORK_INFO="Address: $(grep -v "127" "$HOME_DIR"/node/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $2 }')
Netmask: $(grep -v "127" "$HOME_DIR"/node/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $4 }')
Broadcast: $(grep -v "127" "$HOME_DIR"/node/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $6 }')"
  # if zero
  if [[ -z "$WALLET_NETWORK_INFO" ]] &>/dev/null; then
    WALLET_NETWORK_INFO="No network.."
    dialog --msgbox "$WALLET_NETWORK_INFO" 4 16
  else
    dialog --no-collapse --msgbox "$(echo "$WALLET_NETWORK_INFO" | column -t)" 0 0
  fi

  ;;

################################################################################

"4")

  WALLET_ONION_IP="$(cat "$HOME_DIR"/node/onionip.tmp 2>/dev/null)"
  WALLET_INTERNET_INFO="LAN: $(cat "$HOME_DIR"/node/lanip.tmp 2>/dev/null)
WAN: $(cat "$HOME_DIR"/node/wanip.tmp 2>/dev/null)
TOR: ${WALLET_ONION_IP:0:24}...onion"
  # if zero
  if [[ -z "$WALLET_INTERNET_INFO" ]] &>/dev/null; then
    WALLET_INTERNET_INFO="No network.."
    dialog --msgbox "$WALLET_INTERNET_INFO" 4 16
  else
    dialog --no-collapse --msgbox "$(echo "$WALLET_INTERNET_INFO" | column -t)" 0 0
  fi

  ;;

################################################################################

"5")

  # if missing
  if [[ ! -f "$HOME_DIR"/node/hostnamectl ]] &>/dev/null; then
    echo "$(hostnamectl)" >"$HOME_DIR"/node/hostnamectl
  fi
  WALLET_SYSTEM_INFO="$(cat "$HOME_DIR"/node/hostnamectl 2>/dev/null)"
  # if zero
  if [[ -z "$WALLET_SYSTEM_INFO" ]] &>/dev/null; then
    WALLET_SYSTEM_INFO="No system info"
    dialog --msgbox "$WALLET_SYSTEM_INFO" 4 19
  else
    dialog --no-collapse --msgbox "$WALLET_SYSTEM_INFO" 0 0
  fi

  ;;

################################################################################

"6")

  WALLET_POS_INFO="$(cat "$HOME_DIR"/node/stakes.tmp 2>/dev/null)"
  # if zero
  if [[ -z "$WALLET_POS_INFO" ]] &>/dev/null; then
    WALLET_POS_INFO="No stakes"
    dialog --msgbox "$WALLET_POS_INFO" 4 16
  else
    dialog --no-collapse --msgbox "$(echo "$WALLET_POS_INFO" | column -t)" 0 0
  fi

  ;;
esac

# END
