#!/bin/bash

HEIGHT="12"
WIDTH="23"
CHOICE_HEIGHT="4"
BACKTITLE="FreedomCoin"
TITLE="Freedomnode menu"
MENU="Choose one option:"

OPTIONS=(
  "1" "Balances"
  "2" "Peers"
  "3" "Network"
  "4" "Exit")

CHOICE=$(dialog --clear \
  --backtitle "$BACKTITLE" \
  --title "$TITLE" \
  --menu "$MENU" \
  $HEIGHT $WIDTH $CHOICE_HEIGHT \
  "${OPTIONS[@]}" \
  2>&1 >/dev/tty)

clear
case $CHOICE in
1)
  echo "You chose Option 1"
  ;;
2)
  echo "You chose Option 2"
  ;;
3)
  echo "You chose Option 3"
  ;;
4)
  exit
  ;;
esac

# END
