#!/bin/bash

################################################################################

source /etc/freedom-node/include/time_fix
source /etc/freedom-node/include/display/functions

################################################################################

exec 2>/dev/null
# restore terminal to sane state
trap 'sleep '"${TIME:?}"'; reset; stty sane; clear; tput rmcup' EXIT

# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

################################################################################

ZONES=(
  "Peers:2376:2730:2476:2830"     # connections
  "Balance:1950:1220:2450:1620"   # balances
  "Load:3100:1220:3300:1620"      # system load
  "Intranet:3350:3550:3550:3700"  # intranet
  "WAN:2420:1000:2650:1400"       # internet
  "TxCount:1950:1620:2550:2020"   # transactions
  "FreedomCoin:140:1870:800:2050" # logo
  "Hash:40:2100:4600:2250"        # tx hash
)

################################################################################

# if any data
if [[ -f "$HOME_DIR"/node/touchcoords.tmp ]] &>/dev/null; then
  # get last touch coordinates from tmp file (evemu listener should write here)
  read -r x y <"$HOME_DIR"/node/touchcoords.tmp || exit 0
  ##############################################################################

  # check if the touch falls inside a zone
  for ZONE in "${ZONES[@]}"; do
    IFS=":" read -r LABEL x1 y1 x2 y2 <<<"$ZONE"
    if ((x >= x1 && x <= x2 && y >= y1 && y <= y2)); then
      # handle zone label (display dialog)
      handle_zone "$LABEL"
    fi
  done
fi

# END
