#!/bin/bash

################################################################################

source /etc/freedom-node/include/time_fix

################################################################################

exec 2>/dev/null
# restore terminal to sane state
trap 'sleep '"${TIME:?}"'; reset; stty sane; clear; tput rmcup' EXIT

# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

################################################################################

ZONES=(
  "Peers:2200:2660:2700:3060"     # connections
  "Balance:1950:1220:2450:1620"   # balances
  "Load:3100:1220:3300:1620"      # system load
  "Intranet:3350:3550:3550:3700"  # intranet
  "WAN:2420:1000:2650:1400"       # internet
  "TxCount:1950:1620:2550:2020"   # transactions
  "FreedomCoin:140:1870:800:2050" # logo
  "Hash:40:2100:4600:2250"        # tx hash
)

################################################################################

# if any data
if [[ -f "$HOME_DIR"/node/touchcoords.tmp ]] &>/dev/null; then
  # get last touch coordinates from tmp file (evtest listener should write here)
  read -r x y <"$HOME_DIR"/node/touchcoords.tmp || exit 0
  # handle zone function
  handle_zone() {
    case "$1" in
    ############################################################################
    # peers
    ############################################################################
    Peers)
      WALLET_PEERS_INFO="$(cat /etc/freedom-node/connected.peers 2>/dev/null)"
      # if zero
      if [[ -z "$WALLET_PEERS_INFO" ]] &>/dev/null; then
        WALLET_PEERS_INFO="No peers.."
        dialog --infobox "$WALLET_PEERS_INFO" 4 16
      else
        dialog --infobox "$WALLET_PEERS_INFO" 0 0
      fi
      ;;
      ##########################################################################
      # balance
      ##########################################################################
    Balance)
      WALLET_BALANCES_INFO="$(cat "$HOME_DIR"/node/getwalletinfo.tmp 2>/dev/null | grep "balance" | tr -d ' ,"' | tr ':' ' ' | column -t | tr '_' ' ')"
      # if zero
      if [[ -z "$WALLET_BALANCES_INFO" ]] &>/dev/null; then
        WALLET_BALANCES_INFO="No balances"
        dialog --infobox "$WALLET_BALANCES_INFO" 4 16
      else
        dialog --no-collapse --infobox "$WALLET_BALANCES_INFO" 0 0
      fi
      ;;
      ##########################################################################
      # intranet
      ##########################################################################
    Intranet)
      echo "$(ifconfig 2>/dev/null)" >"$HOME_DIR"/node/ifconfig
      WALLET_NETWORK_INFO="Address: $(grep -v "127" "$HOME_DIR"/node/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $2 }')
    Netmask: $(grep -v "127" "$HOME_DIR"/node/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $4 }')
    Broadcast: $(grep -v "127" "$HOME_DIR"/node/ifconfig 2>/dev/null | grep -A7 "inet " | grep -v "flags" | grep "inet " | awk '{ print $6 }')"
      # if zero
      if [[ -z "$WALLET_NETWORK_INFO" ]] &>/dev/null; then
        WALLET_NETWORK_INFO="No network.."
        dialog --infobox "$WALLET_NETWORK_INFO" 4 16
      else
        dialog --no-collapse --infobox "$(echo "$WALLET_NETWORK_INFO" | column -t)" 0 0
      fi
      ;;
      ##########################################################################
      # internet (WAN)
      ##########################################################################
    WAN)
      WALLET_ONION_IP="$(cat "$HOME_DIR"/node/onionip.tmp 2>/dev/null)"
      WALLET_INTERNET_INFO="LAN: $(cat "$HOME_DIR"/node/lanip.tmp 2>/dev/null)
WAN: $(cat "$HOME_DIR"/node/wanip.tmp 2>/dev/null)
TOR: ${WALLET_ONION_IP:0:24}...onion"
      # if zero
      if [[ -z "$WALLET_INTERNET_INFO" ]] &>/dev/null; then
        WALLET_INTERNET_INFO="No network.."
        dialog --infobox "$WALLET_INTERNET_INFO" 4 16
      else
        dialog --no-collapse --infobox "$(echo "$WALLET_INTERNET_INFO" | column -t)" 0 0
      fi
      ;;
      ##########################################################################
      # system (Load)
      ##########################################################################
    Load)
      # if missing
      if [[ ! -f "$HOME_DIR"/node/hostnamectl ]] &>/dev/null; then
        echo "$(hostnamectl)" >"$HOME_DIR"/node/hostnamectl
      fi
      WALLET_SYSTEM_INFO="$(cat "$HOME_DIR"/node/hostnamectl 2>/dev/null)"
      # if zero
      if [[ -z "$WALLET_SYSTEM_INFO" ]] &>/dev/null; then
        WALLET_SYSTEM_INFO="No system info"
        dialog --infobox "$WALLET_SYSTEM_INFO" 4 19
      else
        dialog --no-collapse --infobox "$WALLET_SYSTEM_INFO" 0 0
      fi
      ;;
      ##########################################################################
      # Proof of stake (PoS)
      ##########################################################################
    POS)
      WALLET_POS_INFO="$(cat "$HOME_DIR"/node/stakes.tmp 2>/dev/null)"
      # if zero
      if [[ -z "$WALLET_POS_INFO" ]] &>/dev/null; then
        WALLET_POS_INFO="No stakes"
        dialog --infobox "$WALLET_POS_INFO" 4 16
      else
        dialog --no-collapse --infobox "$(echo "$WALLET_POS_INFO" | column -t)" 0 0
      fi
      ;;
    esac
    exit
  }
  ##############################################################################

  # check if the touch falls inside a zone
  for ZONE in "${ZONES[@]}"; do
    IFS=":" read -r LABEL x1 y1 x2 y2 <<<"$ZONE"
    if ((x >= x1 && x <= x2 && y >= y1 && y <= y2)); then
      # handle zone label (display dialog)
      handle_zone "$LABEL"
    fi
  done
fi

# END
