#!/bin/bash

################################################################################

source /etc/freedom-node/include/time_fix
source /etc/freedom-node/include/display/functions

################################################################################

exec 2>/dev/null
# restore terminal to sane state
trap 'sleep '"${TIME:?}"'; reset; stty sane; clear; tput rmcup' EXIT

# home directory
HOME_DIR="$(cat /etc/freedom-node/homedir 2>/dev/null)"

################################################################################

ZONES=(
  "2422:2835:2422:2835" # connections
  "1950:1220:2450:1620" # balances
  "3100:1220:3300:1620" # system load
  "3350:3550:3550:3700" # intranet
  "2420:1000:2650:1400" # internet
  "1950:1620:2550:2020" # transactions
  "140:1870:800:2050"   # logo
  "40:2100:4600:2250"   # tx hash
)

################################################################################

# if any data
if [[ -f "$HOME_DIR"/node/touchcoords.tmp ]] &>/dev/null; then
  # get last touch coordinates from tmp file (evemu listener should write here)
  read -r x y <"$HOME_DIR"/node/touchcoords.tmp || exit 0
  ##############################################################################

  # check if the touch falls inside a zone
  for ZONE in "${ZONES[@]}"; do
    IFS=":" read -r x1 y1 x2 y2 <<<"$ZONE"
    if ((x >= x1 && x <= x2 && y >= y1 && y <= y2)); then
      # handle zone
      handle_zone "$ZONE"
    fi
  done
fi

# END
